# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ab46c00aa79cbd1ed193a3313b54ae5655f20ecedd7df248a03a91876121cec0265e9efcc6a59a8503a496d988ce3de40671e3470cf30bd26c6e8db1d49311a

test:
  secret_key_base: 99773f38c7814ae3e729f2672fefe3256f8773376a85f1468412f32de89be480fc0bab3cc1e7d81a122222a89f462b98a139322cf93cce79e78f9ff312f380ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
